### ISSUE TITLE
Unable to listen event inside mat-item

### ISSUE THREAD

**Issue by zarichniuk** [expandjs/mat-checkbox#1]
Unable to listen event `xp-input-change` inside `mat-item` with `primary-type="checkbox"`.

```
        $(document).on('xp-input-change', 'mat-checkbox', function() {
            console.log(1);
        });
```

This code doesn't fire `console.log` on checkbox change

**Comment by grullo90** [comment]
Thanks for the feedback! 

The Issue has been fixed. If you're using bower, clear its cache and reinstall the components.

**Comment by zarichniuk** [comment]
Sorry but issue is still reproducible. Event listener works when it attached to already created `mat-checkbox`. But if it is attached to dynamically created elements it doesn't works.

**Comment by Pupix** [comment]
I've just tested this, using native `addEventListener`, `XP.listen` and jQuery's `on`. The former two worked without any problems, independently of the `mat-checkbox`'s initialization time.

Using your snippet with jQuery never worked, neither with already initialized `mat-checkbox`es nor with dynamically initialized ones.

This being said I conclude that the problem is either jQuery related or your snippet is not written correctly. (Not a fan of jQuery so I couldn't really point out the mistakes.)

Changing `mat-checkbox` with `mat-item` or directly binding the event to `mat-checkbox` worked just fine.

``` html
$(document).on('xp-input-change', 'mat-item', function() {
    console.log(1);
});

$('mat-checkbox').on('xp-input-change', function() {
    console.log(1);
});
```

**Comment by zarichniuk** [comment]
Thanks for answers. You are doing great job. I'll try to find problem and write when i found.

**Comment by zarichniuk** [comment]
Sorry guys it was misunderstanding. I was listening for event on `mat-checkbox` inside `mat-item` instead of listening on `mat-item`. Thought it can be helpful when someone made the same mistake.

**Comment by Pupix** [comment]
No problem, glad we could help.
